// Schema captured from the v1 release for migration tests. Keep this snapshot unchanged; add a migration step when the current schema changes.
// `sqlite_sequence` is omitted because SQLite creates and owns it.

const kSchemaV1 = <String>[
  'CREATE TABLE "bars" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "unit" TEXT NOT NULL, "name" TEXT NOT NULL, "seed_key" TEXT NULL, "weight_kg" REAL NOT NULL, "is_custom" INTEGER NOT NULL DEFAULT 0 CHECK ("is_custom" IN (0, 1)));',
  'CREATE TABLE "custom_themes" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "palette" TEXT NOT NULL);',
  'CREATE TABLE "exercises" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "seed_key" TEXT NULL, "muscle_group" TEXT NOT NULL DEFAULT \'Other\', "equipment" TEXT NOT NULL DEFAULT \'Other\', "video_url" TEXT NULL, "is_custom" INTEGER NOT NULL DEFAULT 0 CHECK ("is_custom" IN (0, 1)), "measure" TEXT NOT NULL DEFAULT \'reps\', "weight_type" TEXT NOT NULL DEFAULT \'machine\', "notes" TEXT NULL, "bar_weight" REAL NULL);',
  'CREATE TABLE "live_sessions" ("id" INTEGER NOT NULL DEFAULT 1, "payload" TEXT NOT NULL, "saved_at" INTEGER NOT NULL, PRIMARY KEY ("id"));',
  'CREATE TABLE "routines" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" TEXT NOT NULL, "seed_key" TEXT NULL, "color_hex" TEXT NOT NULL DEFAULT \'FF6A3D\', "position" INTEGER NOT NULL DEFAULT 0, "rest_seconds" INTEGER NOT NULL DEFAULT 90, "schedule_days" INTEGER NOT NULL DEFAULT 0, "reminder_minutes" INTEGER NULL);',
  'CREATE TABLE "session_sets" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "session_id" INTEGER NOT NULL REFERENCES sessions (id) ON DELETE CASCADE, "exercise_id" INTEGER NULL, "exercise_name" TEXT NOT NULL, "exercise_seed_key" TEXT NULL, "set_number" INTEGER NOT NULL, "weight" REAL NOT NULL DEFAULT 0.0, "reps" INTEGER NOT NULL DEFAULT 0, "done" INTEGER NOT NULL DEFAULT 0 CHECK ("done" IN (0, 1)), "goal_reps" INTEGER NOT NULL DEFAULT 0, "goal_weight" REAL NULL, "seconds" INTEGER NULL, "goal_seconds" INTEGER NULL, "video_path" TEXT NULL);',
  'CREATE TABLE "sessions" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "routine_id" INTEGER NULL, "workout_id" INTEGER NULL, "name" TEXT NOT NULL, "seed_key" TEXT NULL, "started_at" INTEGER NOT NULL, "ended_at" INTEGER NULL, "duration_seconds" INTEGER NOT NULL DEFAULT 0, "total_volume" REAL NOT NULL DEFAULT 0.0, "sets_completed" INTEGER NOT NULL DEFAULT 0);',
  'CREATE TABLE "settings" ("id" INTEGER NOT NULL DEFAULT 1, "weight_unit" TEXT NULL, "active_routine_id" INTEGER NULL, "layoff_days" INTEGER NOT NULL DEFAULT 14, "layoff_percent" INTEGER NOT NULL DEFAULT 10, "plate_inventory" TEXT NULL, "plate_inventory_lb" TEXT NULL, "bar_weight" REAL NULL, "tutorial_seen" INTEGER NOT NULL DEFAULT 0 CHECK ("tutorial_seen" IN (0, 1)), "text_scale" REAL NOT NULL DEFAULT 1.0, "theme_preset_id" TEXT NULL, "video_height" INTEGER NOT NULL DEFAULT 720, "video_max_seconds" INTEGER NOT NULL DEFAULT 60, "locale_tag" TEXT NULL, PRIMARY KEY ("id"));',
  'CREATE TABLE "workout_items" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "workout_id" INTEGER NOT NULL REFERENCES workouts (id) ON DELETE CASCADE, "exercise_id" INTEGER NOT NULL REFERENCES exercises (id), "position" INTEGER NOT NULL DEFAULT 0, "target_sets" INTEGER NOT NULL DEFAULT 3, "reps_min" INTEGER NOT NULL DEFAULT 8, "reps_max" INTEGER NULL, "to_failure" INTEGER NOT NULL DEFAULT 0 CHECK ("to_failure" IN (0, 1)), "rest_seconds" INTEGER NULL, "suggested_weight" REAL NULL, "scheme" TEXT NOT NULL DEFAULT \'flat\', "scheme_percent" INTEGER NOT NULL DEFAULT 10, "custom_sets" TEXT NULL, "progression" TEXT NOT NULL DEFAULT \'weight\', "hold_seconds" INTEGER NOT NULL DEFAULT 30, "increment" REAL NOT NULL DEFAULT 2.5, "success_threshold" INTEGER NOT NULL DEFAULT 1, "deload" REAL NOT NULL DEFAULT 5.0, "failure_threshold" INTEGER NOT NULL DEFAULT 2, "success_streak" INTEGER NOT NULL DEFAULT 0, "fail_streak" INTEGER NOT NULL DEFAULT 0);',
  'CREATE TABLE "workouts" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "routine_id" INTEGER NOT NULL REFERENCES routines (id) ON DELETE CASCADE, "name" TEXT NOT NULL, "seed_key" TEXT NULL, "position" INTEGER NOT NULL DEFAULT 0);',
];
